//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidAutomator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AndroidAutomator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AndroidAutomator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidAutomator.Properties.AndroidAutomator", typeof(AndroidAutomator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appium Driver.
        /// </summary>
        internal static string AndroidDriver {
            get {
                return ResourceManager.GetString("AndroidDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appium Driver to execute commands outside of Android Activity Scope..
        /// </summary>
        internal static string AndroidDriverDesc {
            get {
                return ResourceManager.GetString("AndroidDriverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of Android device..
        /// </summary>
        internal static string AndroidVersionDesc {
            get {
                return ResourceManager.GetString("AndroidVersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndroidVersion.
        /// </summary>
        internal static string AndroidVersionField {
            get {
                return ResourceManager.GetString("AndroidVersionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to target APK file..
        /// </summary>
        internal static string ApkPathDesc {
            get {
                return ResourceManager.GetString("ApkPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APKFilePath.
        /// </summary>
        internal static string ApkPathField {
            get {
                return ResourceManager.GetString("ApkPathField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity to launch in to..
        /// </summary>
        internal static string AppActivityDesc {
            get {
                return ResourceManager.GetString("AppActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppActivity.
        /// </summary>
        internal static string AppActivityField {
            get {
                return ResourceManager.GetString("AppActivityField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the application package..
        /// </summary>
        internal static string AppPackageDesc {
            get {
                return ResourceManager.GetString("AppPackageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppPackage.
        /// </summary>
        internal static string AppPackageField {
            get {
                return ResourceManager.GetString("AppPackageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate backwards in the browser history (if possible)..
        /// </summary>
        internal static string BackActivityDesc {
            get {
                return ResourceManager.GetString("BackActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackActivityName {
            get {
                return ResourceManager.GetString("BackActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of browser that will be launched..
        /// </summary>
        internal static string BrowserTypeDesc {
            get {
                return ResourceManager.GetString("BrowserTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrowserType.
        /// </summary>
        internal static string BrowserTypeField {
            get {
                return ResourceManager.GetString("BrowserTypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to Chromedriver executable. If not provided, whatever version is installed with Appium will be used. Note: if the default version is used, there is a possibility that it will not be compatible to the version of Chrome on your Android device, which will cause the workflow to fail. For more info, go to http://appium.io/docs/en/writing-running-appium/web/chromedriver ..
        /// </summary>
        internal static string ChromedriverPathDesc {
            get {
                return ResourceManager.GetString("ChromedriverPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChromedriverPath.
        /// </summary>
        internal static string ChromedriverPathField {
            get {
                return ResourceManager.GetString("ChromedriverPathField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application in current session..
        /// </summary>
        internal static string CloseAppActivityDesc {
            get {
                return ResourceManager.GetString("CloseAppActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close App.
        /// </summary>
        internal static string CloseAppActivityName {
            get {
                return ResourceManager.GetString("CloseAppActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        internal static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to wait before action is performed in milliseconds..
        /// </summary>
        internal static string DelayDesc {
            get {
                return ResourceManager.GetString("DelayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelayBefore.
        /// </summary>
        internal static string DelayField {
            get {
                return ResourceManager.GetString("DelayField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Android device (can be anything but must be filled)..
        /// </summary>
        internal static string DeviceNameDesc {
            get {
                return ResourceManager.GetString("DeviceNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceName.
        /// </summary>
        internal static string DeviceNameField {
            get {
                return ResourceManager.GetString("DeviceNameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Appium Driver to pass to activities outside of scope..
        /// </summary>
        internal static string DriverDesc {
            get {
                return ResourceManager.GetString("DriverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string DriverField {
            get {
                return ResourceManager.GetString("DriverField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object for target UI element..
        /// </summary>
        internal static string ElementDesc {
            get {
                return ResourceManager.GetString("ElementDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string ElementField {
            get {
                return ResourceManager.GetString("ElementField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X coordinate for swipe destination..
        /// </summary>
        internal static string EndXDesc {
            get {
                return ResourceManager.GetString("EndXDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndX.
        /// </summary>
        internal static string EndXField {
            get {
                return ResourceManager.GetString("EndXField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y coordinate for swipe destination..
        /// </summary>
        internal static string EndYDesc {
            get {
                return ResourceManager.GetString("EndYDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndY.
        /// </summary>
        internal static string EndYField {
            get {
                return ResourceManager.GetString("EndYField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text into a UI element..
        /// </summary>
        internal static string EnterTextActivityDesc {
            get {
                return ResourceManager.GetString("EnterTextActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Text.
        /// </summary>
        internal static string EnterTextActivityName {
            get {
                return ResourceManager.GetString("EnterTextActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be entered into UI element..
        /// </summary>
        internal static string EnterTextDesc {
            get {
                return ResourceManager.GetString("EnterTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to wait for target element to appear..
        /// </summary>
        internal static string ExplicitWaitDesc {
            get {
                return ResourceManager.GetString("ExplicitWaitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename of screenshot. If none is provided, the filename will default to &quot;capture.png&quot;..
        /// </summary>
        internal static string FilenameDesc {
            get {
                return ResourceManager.GetString("FilenameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string FilenameField {
            get {
                return ResourceManager.GetString("FilenameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an element based on ID, Class, or XPath and return the element..
        /// </summary>
        internal static string FindElementActivityDesc {
            get {
                return ResourceManager.GetString("FindElementActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Element.
        /// </summary>
        internal static string FindElementActivityName {
            get {
                return ResourceManager.GetString("FindElementActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate forwards in the browser history (if possible)..
        /// </summary>
        internal static string ForwardActivityDesc {
            get {
                return ResourceManager.GetString("ForwardActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string ForwardActivityName {
            get {
                return ResourceManager.GetString("ForwardActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get text from a UI element..
        /// </summary>
        internal static string GetTextActivityDesc {
            get {
                return ResourceManager.GetString("GetTextActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Text.
        /// </summary>
        internal static string GetTextActivityName {
            get {
                return ResourceManager.GetString("GetTextActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text extracted from UI element..
        /// </summary>
        internal static string GetTextDesc {
            get {
                return ResourceManager.GetString("GetTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to a new URL. .
        /// </summary>
        internal static string GoToURLActivityDesc {
            get {
                return ResourceManager.GetString("GoToURLActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to URL.
        /// </summary>
        internal static string GoToURLActivityName {
            get {
                return ResourceManager.GetString("GoToURLActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of UI element within a list of elements. Only relevant when using MultipleElements..
        /// </summary>
        internal static string IndexDesc {
            get {
                return ResourceManager.GetString("IndexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string IndexField {
            get {
                return ResourceManager.GetString("IndexField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android toolbar button key..
        /// </summary>
        internal static string KeyCodeDesc {
            get {
                return ResourceManager.GetString("KeyCodeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyCode.
        /// </summary>
        internal static string KeyCodeField {
            get {
                return ResourceManager.GetString("KeyCodeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set device language, paired with Locale..
        /// </summary>
        internal static string LanguageDesc {
            get {
                return ResourceManager.GetString("LanguageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageField {
            get {
                return ResourceManager.GetString("LanguageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify whether an app or a web browser should be launched..
        /// </summary>
        internal static string LaunchTypeDesc {
            get {
                return ResourceManager.GetString("LaunchTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaunchType.
        /// </summary>
        internal static string LaunchTypeField {
            get {
                return ResourceManager.GetString("LaunchTypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set device locale, paired with Language..
        /// </summary>
        internal static string LocaleDesc {
            get {
                return ResourceManager.GetString("LocaleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        internal static string LocaleField {
            get {
                return ResourceManager.GetString("LocaleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long press on a UI element..
        /// </summary>
        internal static string LongPressActivityDesc {
            get {
                return ResourceManager.GetString("LongPressActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Press.
        /// </summary>
        internal static string LongPressActivityName {
            get {
                return ResourceManager.GetString("LongPressActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select checkbox if Selector is expected to return multiple elements (eg. using a Class selector will most likely return multiple elements). If selected, the Index property must be entered..
        /// </summary>
        internal static string MultipleElementsDesc {
            get {
                return ResourceManager.GetString("MultipleElementsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultipleElements.
        /// </summary>
        internal static string MultipleElementsField {
            get {
                return ResourceManager.GetString("MultipleElementsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object containing the target UI element as a child..
        /// </summary>
        internal static string ParentDesc {
            get {
                return ResourceManager.GetString("ParentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string ParentField {
            get {
                return ResourceManager.GetString("ParentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Appium driver for current session..
        /// </summary>
        internal static string QuitDriverActivityDesc {
            get {
                return ResourceManager.GetString("QuitDriverActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Driver.
        /// </summary>
        internal static string QuitDriverActivityName {
            get {
                return ResourceManager.GetString("QuitDriverActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the browser page..
        /// </summary>
        internal static string RefreshActivityDesc {
            get {
                return ResourceManager.GetString("RefreshActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshActivityName {
            get {
                return ResourceManager.GetString("RefreshActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope activity for Android Automation. All other Android activities can be placed within this scope to run them. If the activities are to be used outsid of the scope, the Driver field can be used to output the Android Driver which can the be passed into other Android Activities. Parameters for the target Android Device and application/browser can be set here, as well as other options like the root file path for screenshots and Language/Locale..
        /// </summary>
        internal static string ScopeActivityDesc {
            get {
                return ResourceManager.GetString("ScopeActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Activity Scope.
        /// </summary>
        internal static string ScopeActivityName {
            get {
                return ResourceManager.GetString("ScopeActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path for screenshots to be saved in..
        /// </summary>
        internal static string ScreenshotPathDesc {
            get {
                return ResourceManager.GetString("ScreenshotPathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScreenshotPath.
        /// </summary>
        internal static string ScreenshotPathField {
            get {
                return ResourceManager.GetString("ScreenshotPathField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String selector for target UI element..
        /// </summary>
        internal static string SelectorDesc {
            get {
                return ResourceManager.GetString("SelectorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        internal static string SelectorField {
            get {
                return ResourceManager.GetString("SelectorField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set type of selector (ID, Class, or XPath)..
        /// </summary>
        internal static string SelectTypeDesc {
            get {
                return ResourceManager.GetString("SelectTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectorType.
        /// </summary>
        internal static string SelectTypeField {
            get {
                return ResourceManager.GetString("SelectTypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X coordinate for swipe origin..
        /// </summary>
        internal static string StartXDesc {
            get {
                return ResourceManager.GetString("StartXDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartX.
        /// </summary>
        internal static string StartXField {
            get {
                return ResourceManager.GetString("StartXField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y coordinate for swipe origin..
        /// </summary>
        internal static string StartYDesc {
            get {
                return ResourceManager.GetString("StartYDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartY.
        /// </summary>
        internal static string StartYField {
            get {
                return ResourceManager.GetString("StartYField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform a swipe action based on coordinates provided..
        /// </summary>
        internal static string SwipeActivityDesc {
            get {
                return ResourceManager.GetString("SwipeActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe.
        /// </summary>
        internal static string SwipeActivityName {
            get {
                return ResourceManager.GetString("SwipeActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a screenshot of the current screen and save it based on the ScreenshotPath property from the Scope activity. Note: if a file of the same name exists, that file is overwritten without warning..
        /// </summary>
        internal static string TakeScreenshotActivityDesc {
            get {
                return ResourceManager.GetString("TakeScreenshotActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Screenshot.
        /// </summary>
        internal static string TakeScreenshotActivityName {
            get {
                return ResourceManager.GetString("TakeScreenshotActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap on a UI element or coordinates..
        /// </summary>
        internal static string TapActivityDesc {
            get {
                return ResourceManager.GetString("TapActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        internal static string TapActivityName {
            get {
                return ResourceManager.GetString("TapActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextField {
            get {
                return ResourceManager.GetString("TextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides access to the back/home buttons on the Android Toolbar..
        /// </summary>
        internal static string ToolbarActivityDesc {
            get {
                return ResourceManager.GetString("ToolbarActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Toolbar Buttons.
        /// </summary>
        internal static string ToolbarActivityName {
            get {
                return ResourceManager.GetString("ToolbarActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL of the website..
        /// </summary>
        internal static string URLFieldDesc {
            get {
                return ResourceManager.GetString("URLFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URLFieldName {
            get {
                return ResourceManager.GetString("URLFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When True, (X, Y) coordinates are used instead of Element/Selector..
        /// </summary>
        internal static string UseCoordinatesDesc {
            get {
                return ResourceManager.GetString("UseCoordinatesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCoordinates.
        /// </summary>
        internal static string UseCoordinatesField {
            get {
                return ResourceManager.GetString("UseCoordinatesField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force the process to wait for a certain element to appear; based on ID, Class or XPath..
        /// </summary>
        internal static string WaitForElementActivityDesc {
            get {
                return ResourceManager.GetString("WaitForElementActivityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Element.
        /// </summary>
        internal static string WaitForElementActivityName {
            get {
                return ResourceManager.GetString("WaitForElementActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default amount of time (in seconds) the program will wait for elements to appear..
        /// </summary>
        internal static string WaitTimeDesc {
            get {
                return ResourceManager.GetString("WaitTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitTime.
        /// </summary>
        internal static string WaitTimeField {
            get {
                return ResourceManager.GetString("WaitTimeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X coordinate of target UI element..
        /// </summary>
        internal static string XDesc {
            get {
                return ResourceManager.GetString("XDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string XField {
            get {
                return ResourceManager.GetString("XField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y coordinate of target UI element..
        /// </summary>
        internal static string YDesc {
            get {
                return ResourceManager.GetString("YDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string YField {
            get {
                return ResourceManager.GetString("YField", resourceCulture);
            }
        }
    }
}
